# -*- coding: utf-8 -*-
"""GenerativeSystem

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RNVyXIElFe3wcLB4M6JGRyhuOIrqfLxr
"""

from onmt.translate.translator import build_translator
import onmt.opts as opts
from onmt.utis.parse import ArgumentParser
import MeCab
from telegram_bot import TelegramBot


class GenerativeSystem:
  def __init__(self):
    #おまじない
    parser = ArgumentParser()
    opts.config_opts(parser)
    opts.translate_opts(parser)
    self.opt = parser.parser_args()
    ArgumentParser.validate_trnslate_opts(self.opts)
    self.translator = build_translator(self.opt, report_score=True)

    #単語分割用にMeCabを使用
    self.mecab = MeCab.Tagger("-Owakati")
    self.mecab.parse("")

  def initial_message(self, input):
    return {'utt':'こんにちは。対話を始めましょう。','end': False}

  def reply(self, input):
    #単語を分割
    src = [self.mecab.parse(input["utt"])[0:-2]]
    #OpenNMTで応答を生成
    scores, prediction = self.translator.translate(
        src=src,
        tgt=None,
        src_dir=self.opt.src_dir,
        batch_size=self.opt.batch_size,
        attn_debug=False
    )
    # OpenNMTの出力も単語に分割されているので、半角スペースを削除
    utt = prediction[0][0].replace(" ", "")


if __name__ == '__main__':
  system = GenerativeSystem()
  bot = TelegramBot(system)
  bot.run()